In [5]:
import numpy as np

##  Hebbian Learner

In [63]:
#linearly separable data
x = [[1.0,2.5],[2.0,-1.0], [1.5,3.0], [0.0,-1.5], [-3.5,1.0],[2.5,0.0],[0.5,1.5],[0.0,-2.0]]
y = [1,0,1,0,1,0,0,0]


In [114]:
def step(x, bi =False): # x is a vector (1 rank input) 
    ind_less_than_equal_0 = np.where(x<=0)
    ind_more_than_0 = np.where(x>0) #using this instead of sets incase of multi rank inputs
    z = x 
    z[ind_more_than_0] = 1
    if(bi):
        z[ind_less_than_equal_0] = -1
    else:
        z[ind_less_than_equal_0] = 0
    return z


class neuron:
    def __init__(self, x_shape, learning_rate = 0.01): #x_shape is number of inputs #x and y are 2 rank: batch_size*dims
        self.xshape = x_shape 
        self.weights = self.init_weights(x_shape)
        #self.bias = np.random.randn(1)
        self.activation = step #(bi=True)
        self.learning_rate = learning_rate
    def init_weights(self, n0):
        return np.random.randn(1,n0) #n1 is number of input neurons
    def output(self, x): #equivalent to forward pass/activation
        pred = self.activation(np.dot(x,np.transpose(self.weights)),False)# + self.bias)
        return pred
    def param_updates(self, preds, x):
        #using formula that delta(weight_i) = learning_rate*(X_i*Y_i +|Y_i-X_i|)
        #assume preds to be shape batch_size*1
        #BELOW formula assumes weights are only updated after entire batch
        self.weights = self.weights + self.learning_rate*np.average(preds*x) #on average activations were so and so
        #self.bias = self.bias + self.lear
            
    def training(self, x,y): #taking y although it is irrelevant for a pure hebbian learner
        x = np.array(x)
        preds = self.output(x)
        preds = preds.reshape(preds.shape[0],1)
        self.param_updates(preds, x)


In [115]:
hebbian_neuron = neuron(2)

In [116]:
hebbian_neuron.training(x,y)

In [117]:
hebbian_neuron.weights 

array([[-0.28007653, -0.59577225]])

In [118]:
hebbian_neuron.output([-5,-1.5])

array([ 1.])

In [97]:
np.average(preds*x, axis=0)

array([ 0.625 ,  0.0625])

In [96]:
preds*x

array([[-1. , -2.5],
       [-2. ,  1. ],
       [ 1.5,  3. ],
       [ 0. , -1.5],
       [ 3.5, -1. ],
       [ 2.5,  0. ],
       [ 0.5,  1.5],
       [ 0. , -0. ]])